### ISSUE TITLE
API Endpoint for Languages

### ISSUE THREAD

**Issue by NickEngmann** [opensandiego/p2p-lending#16]
An endpoint to return an array of different languages that currently exist in the database, and how the number of titles that are attached to each of those titles would be very helpful.

**Comment by danortega13** [comment]
Will be attempting to solve this issue. Any pointers would be greatly appreciated though =D

**Comment by nikolajbaer** [comment]
An approach would be to create a ["Manager" ](https://docs.djangoproject.com/en/2.2/topics/db/managers/#custom-managers)on the Title model that returns all active languages with a distinct [values query](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#values-list), e.g.

`languages_available = Title.objects.values_list("language").distinct()`

You probably then want to merge this with the LANGUAGES list, and serve in an [APIView ](https://www.django-rest-framework.org/api-guide/views/) from lending/views.py.

If you want to get fancy, you can also use [annotate](https://docs.djangoproject.com/en/2.2/topics/db/aggregation/#generating-aggregates-for-each-item-in-a-queryset) to add in the count of Titles per each language, which is something like `Title.objects.all().values_list("language").annotate(cnt=Count("*")).distinct()`

**Comment by nikolajbaer** [comment]
Ok this is now available on the endpoint:

/api/v1/available-languages/

It returns a list of languages currently represented by the titles, with language code (e.g. "es"), language display name (e.g. "Spanish"), and a count of titles for that language.

**Comment by nikolajbaer** [comment]
Additional note: I wired this up in the frontend so the root language list now pulls from the DB, not a static list. 

When it comes to filtering the actual titles, we need to be pulling that in with /titles/?language={key} where key is a prop on the LanguageItem (pulled from "language" in the result of available-languages)

**Comment by NickEngmann** [comment]
Great work! Going to push a solution for edge cases, in case there are some titles in the database without languages/codes/language/display elements
