### ISSUE TITLE
Login Form via API

### ISSUE THREAD

**Issue by nikolajbaer** [opensandiego/p2p-lending#21]
Adding this task (which i have already started on).

There is already an API endpoint for this (/api-auth/login/). The next steps are:

- [x] add to backendCalls
- [x] create LoginModal
- [x] deal with CSRF Token (it is in the session cookie, and must be submitted as part of the login API call
- [ ] somehow indicate login status to the overall React App (@NickEngmann I probably need your thoughts on this, as I haven't really figured out yet where global frontend app state is being managed, if it even is/does get managed)
- [ ] maybe add some user-state information in the API response to fill in a nav header (e.g. user full name, current loans, notifications of books waiting for pickup, etc, avatar.. ).

**Comment by nikolajbaer** [comment]
LoginForm now does the login, although the react flow might need some refactoring.

Process is:
1. getCSRFToken - gets the CSRF token that we need to do a POST request
2. submitLogin - submits username/password (with X-CSRFToken header)
3. On success, returns a "key" that we can use to do authenticated requests. However session authentication is also in place so we can also keep making requests without the key (the session is automatically passed through by the browser). 
4. On error - shows error message to user

Note: once the user logs in, the backend changes the CSRF token ,so we will need to update and store this.

There is also an API call for "fetchUserProfile". This returns 404 if the user is not logged in, or the user's details if they are logged in.

Things still needed:
- [ ] Update Header Bar to show user's profile status or login buttons
- [ ] Store CSRF token for later use on all POST, PUT, DELETE and PATCH requests
- [ ] Detect logged-in status on page load (maybe stash user details in localStorage)?

**Comment by NickEngmann** [comment]
Hey @nikolajbaer is it correct to assume that if the user has a key then they are logged in? Meaning could I make a method that checks for that key that's stored in localStorage or as a cookie, and if it's there I assume the user is logged in, and then make the appropriate POST/GET/PUT/DELETE/etc. requests from there.

**Comment by nikolajbaer** [comment]
Actually, the key is superfluous. 

The best check for status is to check fetchUserProfile. If it returns a 404, then the user is not logged in, if it returns their profile data, they are logged in. The Session authentication will do the rest.

**Comment by nikolajbaer** [comment]
Closing this, as it looks like login is working now.
