### ISSUE TITLE
Fix Search Bar Routing

### ISSUE THREAD

**Issue by NickEngmann** [opensandiego/p2p-lending#27]
Currently you cannot route twice using the search bar. Meaning that if you put in a search term, and hit enter you will end up on a search results page. But on that results page, if you put in a new search term and hit enter, the url changes but the components aren't reloaded.

Need to look into a different way to look into pushing history changes

For example:
<img width="568" alt="Screen Shot 2019-05-23 at 11 40 01 PM" src="https://user-images.githubusercontent.com/1075072/58307632-20d62080-7db4-11e9-8347-fc1ee5f2d443.png">
Notice how the url has the search term epic inside it, but the components are redenered with the previous term "adventure"

To replicate:
Search a term and hit enter to go to the search results page (the page that shows multiple titles)
Then search another term and hit enter. The URL changes but the content of the site does not

**Comment by alvinherot** [comment]
I will be trying to look into this issue.
