### ISSUE TITLE
Redesign Browse By Language Component

### ISSUE THREAD

**Issue by NickEngmann** [opensandiego/p2p-lending#28]
The Browse by Language component (located in components/BrowseByLanguage.js) could use a redesign

Currently looks like:
<img width="465" alt="Screen Shot 2019-05-23 at 11 29 33 PM" src="https://user-images.githubusercontent.com/1075072/58307228-ed46c680-7db2-11e9-9f5b-f9feea355758.png">

Something more modern/eye attention grabbing would be great. Maybe flag emojis that correlate to the language instead of dot emojis:
For Example:

from -> ⚈ Spanish
to -> 🇪🇸Spanish

**Comment by CarlGraff** [comment]
OK I can take this on - should have it done by tomorrow
