### ISSUE TITLE
Associate Language with a Flag Dictionary

### ISSUE THREAD

**Issue by NickEngmann** [opensandiego/p2p-lending#30]
We are planning to have book titles in multiple languages in this application. It would be helpful to foreign users to also be able to quickly identify if a book is in their language by using flags.

Right now in the Title Results search view we have this:
<img width="177" alt="Screen Shot 2019-05-24 at 12 09 35 AM" src="https://user-images.githubusercontent.com/1075072/58309146-3b11fd80-7db8-11e9-8436-43e9c05745d7.png">
Where the language shorthand appears in the bottom right hand corner. Maybe we also have a flag icon appear by it?

For example:
Instead of just [ES]
We have 🇪🇸[ES]
Related to Issue #11

**Comment by nikolajbaer** [comment]
The only issue I see here is that languages and flags are not consistent. E.g. Spanish is not always Spain, and English is not always the UK

**Comment by NickEngmann** [comment]
very true, there is a handful of languages that have multiple country associations. I still think it would be a neat feature and add a cool UI/UX element to the site.

**Comment by CarlGraff** [comment]
I can do this by reusing the  getFlag function in utilities. Basically it maps some of the languages that have multiple countries to an aceptable flag. For example the many spanish variants are mapped to the spanish flag.

**Comment by NickEngmann** [comment]
Yup, I think it would be another great utilization of that function
