### ISSUE TITLE
Fix Mobile View for Login Modal

### ISSUE THREAD

**Issue by NickEngmann** [opensandiego/p2p-lending#33]
The Login Button on the Login Modal needs to be centered on mobile view/widths less than 800 px
<img width="590" alt="Screen Shot 2019-05-24 at 7 25 45 PM" src="https://user-images.githubusercontent.com/1075072/58363494-c0012380-7e59-11e9-934f-c99466afecba.png">

Needs some old fashion CSS/bootstrap assistance

**Comment by CarlGraff** [comment]
working on this now

**Comment by NickEngmann** [comment]
@nikolajbaer added a username/password form to the overall layout so please take that into consideration with your design choices:

<img width="724" alt="Screen Shot 2019-05-27 at 9 49 27 AM" src="https://user-images.githubusercontent.com/1075072/58431942-e7780c00-8064-11e9-9e85-213511562d04.png">

**Comment by CarlGraff** [comment]
![image](https://user-images.githubusercontent.com/17060133/58923709-a1224d00-86f5-11e9-9d73-6bf3bb70328c.png)

**Comment by NickEngmann** [comment]
Looking good, can you change that submit button to be a bootstrap button though?
For example:
`<button className="btn btn-success">Submit</button>`
