### ISSUE TITLE
Fix Individual Title Page Routing

### ISSUE THREAD

**Issue by NickEngmann** [opensandiego/p2p-lending#36]
Similar to Issue #27 

If you reroute to the Individual Title Page from the Individual Title page, the search URL changes but the content on the page doesn't. The solution to Issue #27 could be used to solve this.

To replicate:
Search a title and click it to end up on the individual title page. 
Afterwards, search for a different title on the same page and click on that title. The URL changes but the content of the site does not.

**Comment by alvinherot** [comment]
Will do this one.
