### ISSUE TITLE
Create demo data

### ISSUE THREAD

**Issue by nikolajbaer** [opensandiego/p2p-lending#4]
Add [Django Management Command](https://docs.djangoproject.com/en/2.2/howto/custom-management-commands/) to generate some demo data for testing. FactoryBoy is already installed so this might be a good base, but the goal is to fill in data so that we can explore / test the UI / UX.

**Comment by nikolajbaer** [comment]
Current command is "generate_test_data". 

Things left to do:
1. Make it use only a couple locations
2. Make it generate Loans and TitleRequests
3. Make it generate some multiple-item lenders

**Comment by BolunThompson** [comment]
For this, should I just use one number to indicate how many loans, title requests, and titles to generate or should I have separate specifications for each of them? Also when you say "multi-item lenders", you mean a profile with multiple items attached to it, correct?
