### ISSUE TITLE
Develop front-end experience

### ISSUE THREAD

**Issue by nikolajbaer** [opensandiego/p2p-lending#5]
Build out front-end user workflow:

- [x] homepage
- [x] title listing / results (e.g. search, or browse by language)
- [x] title detail (with request button)
- [x] login
- [x] account home
- [ ] account my-loans
- [ ] account my-items
- [ ] account my-requests
- [x] create-account (just callout to visit library to setup account)

and maybe also landing pages
- [x] about
- [x] privacy / terms
- [ ] contact

**Comment by NickEngmann** [comment]
Moved about and privacy/terms landing pagers to their own issues

**Comment by alvinherot** [comment]
Hi, I am new to open source and wanting to learn some react. Is there some simple react components I can work on here?

**Comment by NickEngmann** [comment]
The easiest thing to start on in my opinion would be getting some static pages like a privacy page done. Take a look at Issue #9 and some design tips from Issue #25. In the next few days I'll also be making some individual Issues for all the account related components that need to be created, so check back next week if your interested in working on those

**Comment by nikolajbaer** [comment]
I am going to close this issue in favor of individual issues for each view / UX element that needs to get done.
