### ISSUE TITLE
Develop Privacy Page

### ISSUE THREAD

**Issue by NickEngmann** [opensandiego/p2p-lending#9]
Develop a pretty standard Privacy Page that just displays a basic privacy policy the application and is linked to via the footer.
Also in need of a [Sketch](https://www.sketch.com/) design for this page.

**Comment by CarlGraff** [comment]
I can start this tomorrow

**Comment by CarlGraff** [comment]
Here is a website with information on free and paid privacy/policy/terms/conditions generators:
https://thelegality.com/reviews/best-privacy-policy-generators/
To get the ball rolling will start with one based on output from the simplist one that is 100% free:
**You view a sample Pricacy Policy here:**
https://app-privacy-policy-generator.firebaseapp.com/
**and a sample Terems and Conditions here:**
https://app-privacy-policy-generator.firebaseapp.com/
